databases:
  - name: cruize
  - databaseName: cruize
  - user: tomi

services:
  - type: web
    name: mysite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cruize
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false